version: '3'
services:
    db:
        container_name: mongodb
        image: mongo
        ports:
            - '27017:27017'
    server:
        container_name: wine
        restart: always
        build: .
        ports:
            - '8000:8000'
        links:
            - db

